--- #YAML:1.0
name:                String-Tests
version:             0.03
abstract:            run a series of tests on a string
license:             ~
author:              
    - Shaun Fryer <pause.cpan.org@sourcery.ca>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
